version: "3"

services:
    jenkins:
        container_name: jenkins
        build: jenkins/
        ports:
        - "8080:8080"
        environment:
        - JAVA_OPTS:-Djava.awt.headless=true
        volumes:
        - /c/Users/Facundo-Zenbook/docker/jenkins_home:/var/jenkins_home
    db:
        container_name: mysql
        image: mysql:8.0
        ports:
        - "3306:3306"
       
        volumes:
        - /c/Users/Facundo-Zenbook/docker/mysql_server:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD="faculbsz"
        - MYSQL_USER="sa"
        - MYSQL_PASS="faculbsz22"
        - MYSQL_DATABASE="sonar"
    sonarqube:
        depends_on:
        - "db"
        container_name: sonarqube
        image: sonarqube:lts
        environment:
        - SONARQUBE_JDBC_USERNAME="sa"
        - SONARQUBE_JDBC_PASSWORD="faculbsz22"
        - SONARQUBE_JDBC_URL="jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8"
        ports:
        - "9000:9000"
        - "9092:9092"
        volumes:
        - /c/Users/Facundo-Zenbook/docker/sonarqube/conf:/opt/sonarqube/conf
        - /c/Users/Facundo-Zenbook/docker/sonarqube/data:/opt/sonarqube/data
        - /c/Users/Facundo-Zenbook/docker/sonarqube/extensions:/opt/sonarqube/extensions
        - /c/Users/Facundo-Zenbook/docker/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
       