version: "3"

services:
    jenkins:
        container_name: jenkins
        image: faculbsz/jenkins_jdk8_mvn_plugins
        ports:
        - "8090:8080"
        environment:
        - JAVA_OPTS:-Djava.awt.headless=true
        volumes:
        - /c/Users/Admin/docker/jenkins_home:/var/jenkins_home
        links:
        - sonarqube:sonarqube
    sonarqube:
        depends_on:
        - mysql
        restart: always
        container_name: sonarqube
        image: sonarqube:lts
        environment:
        - SONARQUBE_JDBC_USERNAME=sonarqube
        - SONARQUBE_JDBC_PASSWORD=sonarqube
        - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
        ports:
        - "9000:9000"
        - "9092:9092"
        volumes:
        - /c/Users/Admin/docker/sonarqube/conf:/opt/sonarqube/conf
        - /c/Users/Admin/docker/sonarqube/data:/opt/sonarqube/data
        - /c/Users/Admin/docker/sonarqube/extensions:/opt/sonarqube/extensions
        - /c/Users/Admin/docker/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    mysql:
        container_name: mysql
        image: mysql:5.6
        hostname: mysql
        ports:
        - "3306:3306"
        volumes:
        - /c/Users/Admin/docker/mysql_server:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=sonarqube
        - MYSQL_USER=sonarqube
        - MYSQL_PASSWORD=sonarqube
        - MYSQL_DATABASE=sonarqube